import { Routes } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard.component';

export const routes: Routes = [
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', component: DashboardComponent },
    { path: 'angular-architecture', loadComponent: () => import('./topics/angular-architecture/angular-architecture.component').then(m => m.AngularArchitectureComponent) },
    { path: 'angular-cli-commands', loadComponent: () => import('./topics/angular-cli-commands/angular-cli-commands.component').then(m => m.AngularCliCommandsComponent) },
    { path: 'module-system', loadComponent: () => import('./topics/module-system/module-system.component').then(m => m.ModuleSystemComponent) },
    { path: 'standalone-components', loadComponent: () => import('./topics/standalone-components/standalone-components.component').then(m => m.StandaloneComponentsComponent) },
    { path: 'component-lifecycle-hooks', loadComponent: () => import('./topics/component-lifecycle-hooks/component-lifecycle-hooks.component').then(m => m.ComponentLifecycleHooksComponent) },
    { path: 'change-detection-mechanism', loadComponent: () => import('./topics/change-detection-mechanism/change-detection-mechanism.component').then(m => m.ChangeDetectionMechanismComponent) },
    { path: 'zone-js-role', loadComponent: () => import('./topics/zone-js-role/zone-js-role.component').then(m => m.ZoneJsRoleComponent) },
    { path: 'ivy-compiler', loadComponent: () => import('./topics/ivy-compiler/ivy-compiler.component').then(m => m.IvyCompilerComponent) },
    { path: 'aot-vs-jit-compilation', loadComponent: () => import('./topics/aot-vs-jit-compilation/aot-vs-jit-compilation.component').then(m => m.AotVsJitCompilationComponent) },
    { path: 'template-syntax', loadComponent: () => import('./topics/template-syntax/template-syntax.component').then(m => m.TemplateSyntaxComponent) },
    { path: 'interpolation', loadComponent: () => import('./topics/interpolation/interpolation.component').then(m => m.InterpolationComponent) },
    { path: 'property-binding', loadComponent: () => import('./topics/property-binding/property-binding.component').then(m => m.PropertyBindingComponent) },
    { path: 'event-binding', loadComponent: () => import('./topics/event-binding/event-binding.component').then(m => m.EventBindingComponent) },
    { path: 'two-way-binding', loadComponent: () => import('./topics/two-way-binding/two-way-binding.component').then(m => m.TwoWayBindingComponent) },
    { path: 'structural-directives', loadComponent: () => import('./topics/structural-directives/structural-directives.component').then(m => m.StructuralDirectivesComponent) },
    { path: 'attribute-directives', loadComponent: () => import('./topics/attribute-directives/attribute-directives.component').then(m => m.AttributeDirectivesComponent) },
    { path: 'custom-directives', loadComponent: () => import('./topics/custom-directives/custom-directives.component').then(m => m.CustomDirectivesComponent) },
    { path: 'pipes', loadComponent: () => import('./topics/pipes/pipes.component').then(m => m.PipesComponent) },
    { path: 'pure-vs-impure-pipes', loadComponent: () => import('./topics/pure-vs-impure-pipes/pure-vs-impure-pipes.component').then(m => m.PureVsImpurePipesComponent) },
    { path: 'custom-pipes', loadComponent: () => import('./topics/custom-pipes/custom-pipes.component').then(m => m.CustomPipesComponent) },
    { path: 'viewencapsulation', loadComponent: () => import('./topics/viewencapsulation/viewencapsulation.component').then(m => m.ViewencapsulationComponent) },
    { path: 'content-projection', loadComponent: () => import('./topics/content-projection/content-projection.component').then(m => m.ContentProjectionComponent) },
    { path: 'dependency-injection-system', loadComponent: () => import('./topics/dependency-injection-system/dependency-injection-system.component').then(m => m.DependencyInjectionSystemComponent) },
    { path: 'provider-scopes', loadComponent: () => import('./topics/provider-scopes/provider-scopes.component').then(m => m.ProviderScopesComponent) },
    { path: 'hierarchical-injectors', loadComponent: () => import('./topics/hierarchical-injectors/hierarchical-injectors.component').then(m => m.HierarchicalInjectorsComponent) },
    { path: 'services', loadComponent: () => import('./topics/services/services.component').then(m => m.ServicesComponent) },
    { path: 'httpclient', loadComponent: () => import('./topics/httpclient/httpclient.component').then(m => m.HttpclientComponent) },
    { path: 'interceptors', loadComponent: () => import('./topics/interceptors/interceptors.component').then(m => m.InterceptorsComponent) },
    { path: 'error-handling-httpclient', loadComponent: () => import('./topics/error-handling-httpclient/error-handling-httpclient.component').then(m => m.ErrorHandlingHttpclientComponent) },
    { path: 'rxjs-fundamentals', loadComponent: () => import('./topics/rxjs-fundamentals/rxjs-fundamentals.component').then(m => m.RxjsFundamentalsComponent) },
    { path: 'observables-vs-promises', loadComponent: () => import('./topics/observables-vs-promises/observables-vs-promises.component').then(m => m.ObservablesVsPromisesComponent) },
    { path: 'subjects', loadComponent: () => import('./topics/subjects/subjects.component').then(m => m.SubjectsComponent) },
    { path: 'behaviorsubject', loadComponent: () => import('./topics/behaviorsubject/behaviorsubject.component').then(m => m.BehaviorsubjectComponent) },
    { path: 'replaysubject', loadComponent: () => import('./topics/replaysubject/replaysubject.component').then(m => m.ReplaysubjectComponent) },
    { path: 'async-pipe', loadComponent: () => import('./topics/async-pipe/async-pipe.component').then(m => m.AsyncPipeComponent) },
    { path: 'rxjs-operators', loadComponent: () => import('./topics/rxjs-operators/rxjs-operators.component').then(m => m.RxjsOperatorsComponent) },
    { path: 'subscription-management', loadComponent: () => import('./topics/subscription-management/subscription-management.component').then(m => m.SubscriptionManagementComponent) },
    { path: 'memory-leaks-angular', loadComponent: () => import('./topics/memory-leaks-angular/memory-leaks-angular.component').then(m => m.MemoryLeaksAngularComponent) },
    { path: 'reactive-forms', loadComponent: () => import('./topics/reactive-forms/reactive-forms.component').then(m => m.ReactiveFormsComponent) },
    { path: 'template-driven-forms', loadComponent: () => import('./topics/template-driven-forms/template-driven-forms.component').then(m => m.TemplateDrivenFormsComponent) },
    { path: 'form-validation', loadComponent: () => import('./topics/form-validation/form-validation.component').then(m => m.FormValidationComponent) },
    { path: 'custom-validators', loadComponent: () => import('./topics/custom-validators/custom-validators.component').then(m => m.CustomValidatorsComponent) },
    { path: 'formarray', loadComponent: () => import('./topics/formarray/formarray.component').then(m => m.FormarrayComponent) },
    { path: 'dynamic-forms', loadComponent: () => import('./topics/dynamic-forms/dynamic-forms.component').then(m => m.DynamicFormsComponent) },
    { path: 'controlvalueaccessor', loadComponent: () => import('./topics/controlvalueaccessor/controlvalueaccessor.component').then(m => m.ControlvalueaccessorComponent) },
    { path: 'routing-module', loadComponent: () => import('./topics/routing-module/routing-module.component').then(m => m.RoutingModuleComponent) },
    { path: 'lazy-loading-modules', loadComponent: () => import('./topics/lazy-loading-modules/lazy-loading-modules.component').then(m => m.LazyLoadingModulesComponent) },
    { path: 'standalone-route-configuration', loadComponent: () => import('./topics/standalone-route-configuration/standalone-route-configuration.component').then(m => m.StandaloneRouteConfigurationComponent) },
    { path: 'route-guards', loadComponent: () => import('./topics/route-guards/route-guards.component').then(m => m.RouteGuardsComponent) },
    { path: 'resolvers', loadComponent: () => import('./topics/resolvers/resolvers.component').then(m => m.ResolversComponent) },
    { path: 'preloading-strategies', loadComponent: () => import('./topics/preloading-strategies/preloading-strategies.component').then(m => m.PreloadingStrategiesComponent) },
    { path: 'nested-routing', loadComponent: () => import('./topics/nested-routing/nested-routing.component').then(m => m.NestedRoutingComponent) },
    { path: 'route-reuse-strategy', loadComponent: () => import('./topics/route-reuse-strategy/route-reuse-strategy.component').then(m => m.RouteReuseStrategyComponent) },
    { path: 'state-management-concepts', loadComponent: () => import('./topics/state-management-concepts/state-management-concepts.component').then(m => m.StateManagementConceptsComponent) },
    { path: 'ngrx-store', loadComponent: () => import('./topics/ngrx-store/ngrx-store.component').then(m => m.NgrxStoreComponent) },
    { path: 'ngrx-effects', loadComponent: () => import('./topics/ngrx-effects/ngrx-effects.component').then(m => m.NgrxEffectsComponent) },
    { path: 'ngrx-entity', loadComponent: () => import('./topics/ngrx-entity/ngrx-entity.component').then(m => m.NgrxEntityComponent) },
    { path: 'ngrx-selectors', loadComponent: () => import('./topics/ngrx-selectors/ngrx-selectors.component').then(m => m.NgrxSelectorsComponent) },
    { path: 'redux-pattern-angular', loadComponent: () => import('./topics/redux-pattern-angular/redux-pattern-angular.component').then(m => m.ReduxPatternAngularComponent) },
    { path: 'signals', loadComponent: () => import('./topics/signals/signals.component').then(m => m.SignalsComponent) },
    { path: 'computed-signals', loadComponent: () => import('./topics/computed-signals/computed-signals.component').then(m => m.ComputedSignalsComponent) },
    { path: 'signal-vs-rxjs', loadComponent: () => import('./topics/signal-vs-rxjs/signal-vs-rxjs.component').then(m => m.SignalVsRxjsComponent) },
    { path: 'component-communication', loadComponent: () => import('./topics/component-communication/component-communication.component').then(m => m.ComponentCommunicationComponent) },
    { path: 'input-output', loadComponent: () => import('./topics/input-output/input-output.component').then(m => m.InputOutputComponent) },
    { path: 'viewchild-contentchild', loadComponent: () => import('./topics/viewchild-contentchild/viewchild-contentchild.component').then(m => m.ViewchildContentchildComponent) },
    { path: 'hostlistener-hostbinding', loadComponent: () => import('./topics/hostlistener-hostbinding/hostlistener-hostbinding.component').then(m => m.HostlistenerHostbindingComponent) },
    { path: 'trackby-ngfor', loadComponent: () => import('./topics/trackby-ngfor/trackby-ngfor.component').then(m => m.TrackbyNgforComponent) },
    { path: 'virtual-scrolling', loadComponent: () => import('./topics/virtual-scrolling/virtual-scrolling.component').then(m => m.VirtualScrollingComponent) },
    { path: 'angular-cdk', loadComponent: () => import('./topics/angular-cdk/angular-cdk.component').then(m => m.AngularCdkComponent) },
    { path: 'performance-optimization-techniques', loadComponent: () => import('./topics/performance-optimization-techniques/performance-optimization-techniques.component').then(m => m.PerformanceOptimizationTechniquesComponent) },
    { path: 'internationalization', loadComponent: () => import('./topics/internationalization/internationalization.component').then(m => m.InternationalizationComponent) },
    { path: 'security', loadComponent: () => import('./topics/security/security.component').then(m => m.SecurityComponent) },
    { path: 'domsanitizer', loadComponent: () => import('./topics/domsanitizer/domsanitizer.component').then(m => m.DomsanitizerComponent) },
    { path: 'environment-configuration', loadComponent: () => import('./topics/environment-configuration/environment-configuration.component').then(m => m.EnvironmentConfigurationComponent) },
    { path: 'build-optimization', loadComponent: () => import('./topics/build-optimization/build-optimization.component').then(m => m.BuildOptimizationComponent) },
    { path: 'differential-loading', loadComponent: () => import('./topics/differential-loading/differential-loading.component').then(m => m.DifferentialLoadingComponent) },
    { path: 'testing-jasmine', loadComponent: () => import('./topics/testing-jasmine/testing-jasmine.component').then(m => m.TestingJasmineComponent) },
    { path: 'karma-basics', loadComponent: () => import('./topics/karma-basics/karma-basics.component').then(m => m.KarmaBasicsComponent) },
    { path: 'unit-testing-components', loadComponent: () => import('./topics/unit-testing-components/unit-testing-components.component').then(m => m.UnitTestingComponentsComponent) },
    { path: 'service-testing', loadComponent: () => import('./topics/service-testing/service-testing.component').then(m => m.ServiceTestingComponent) },
    { path: 'mocking-httpclient', loadComponent: () => import('./topics/mocking-httpclient/mocking-httpclient.component').then(m => m.MockingHttpclientComponent) },
    { path: 'e2e-testing-basics', loadComponent: () => import('./topics/e2e-testing-basics/e2e-testing-basics.component').then(m => m.E2eTestingBasicsComponent) },
    { path: 'accessibility', loadComponent: () => import('./topics/accessibility/accessibility.component').then(m => m.AccessibilityComponent) },
    { path: 'angular-material', loadComponent: () => import('./topics/angular-material/angular-material.component').then(m => m.AngularMaterialComponent) },
    { path: 'custom-theming', loadComponent: () => import('./topics/custom-theming/custom-theming.component').then(m => m.CustomThemingComponent) },
    { path: 'monorepo-basics', loadComponent: () => import('./topics/monorepo-basics/monorepo-basics.component').then(m => m.MonorepoBasicsComponent) },
    { path: 'micro-frontend-basics', loadComponent: () => import('./topics/micro-frontend-basics/micro-frontend-basics.component').then(m => m.MicroFrontendBasicsComponent) },
    { path: 'folder-structure-best-practices', loadComponent: () => import('./topics/folder-structure-best-practices/folder-structure-best-practices.component').then(m => m.FolderStructureBestPracticesComponent) },
    { path: 'feature-based-architecture', loadComponent: () => import('./topics/feature-based-architecture/feature-based-architecture.component').then(m => m.FeatureBasedArchitectureComponent) },
    { path: 'ssr-angular-universal', loadComponent: () => import('./topics/ssr-angular-universal/ssr-angular-universal.component').then(m => m.SsrAngularUniversalComponent) },
];



